

POST http://localhost:3030/auth/signup
Content-Type: application/json

{
    "email": "guru@gmail.com",
    "password": "123456"
}

### Signin user
POST http://localhost:3030/auth/signin
Content-Type: application/json

{
    "email": "guru@gmail.com",
    "password": "123456"
}

### Signout user
POST http://localhost:3030/auth/signout

### Who am I
GET http://localhost:3030/auth/whoami


### Find a particular user with ID
GET http://localhost:3030/auth/4


### Find all users with query params
GET http://localhost:3030/auth



### Update user info
PUT http://localhost:3030/auth/2
Content-Type: application/json

{
    "email": "madhavi@gmail.com",
    "password": "12345"
}


### Delete a particular user with ID
DELETE http://localhost:3030/auth/2